export { createTMDB, TMDBClient, type TMDBFactoryOptions } from './client'
export {
  TMDBError,
  TMDBRateLimitError,
  TMDBRequestError,
  TMDBResponseError,
} from './errors'
export { buildImageUrl } from './query'
export {
  isMovie,
  isMovieSearchResult,
  isPerson,
  isPersonSearchResult,
  isTV,
  isTVSearchResult,
} from './search-guards'
export {
  isKnownBackdropSize,
  isKnownImageSize,
  isKnownLogoSize,
  isKnownPosterSize,
  isKnownProfileSize,
  isKnownStillSize,
  KNOWN_BACKDROP_SIZES,
  KNOWN_IMAGE_SIZES,
  KNOWN_LOGO_SIZES,
  KNOWN_POSTER_SIZES,
  KNOWN_PROFILE_SIZES,
  KNOWN_STILL_SIZES,
} from './types'
export type { ImageUrlTransform } from './resources/images'

export type {
  FetchLike,
  TMDBAccessTokenAuth,
  TMDBApiKeyAuth,
  TMDBAuth,
  TMDBClientOptions,
  TMDBImagesOptions,
  TMDBRequestOptions,
  TMDBTransport,
} from './http'

export type {
  BackdropSize,
  CollectionSummary,
  Configuration,
  ConfigurationImages,
  Country,
  CreditCastMember,
  CreditCrewMember,
  CreditsResponse,
  Genre,
  GenresResponse,
  ImageItem,
  ImageQueryOptions,
  ImagesResponse,
  ImageSize,
  JobDepartment,
  KnownBackdropSize,
  KnownImageSize,
  KnownLogoSize,
  KnownPosterSize,
  KnownProfileSize,
  KnownStillSize,
  Language,
  LanguageCode,
  LanguageOptions,
  ListOptions,
  LogoSize,
  MediaType,
  MovieAppendToResponse,
  MovieDetails,
  MovieDetailsOptions,
  MovieSearchOptions,
  MovieSearchResult,
  MovieMultiResult,
  MovieSummary,
  MultiSearchOptions,
  Network,
  PagedResponse,
  PersonDetails,
  PersonKnownFor,
  PersonKnownForMovie,
  PersonKnownForTV,
  PersonMultiResult,
  PersonSearchResult,
  PersonSummary,
  PosterSize,
  ProductionCompany,
  ProductionCountry,
  ProfileSize,
  RegionCode,
  SearchMultiResult,
  TVMultiResult,
  EpisodeGuestStar,
  EpisodeSummary,
  SeasonSummary,
  SpokenLanguage,
  StillSize,
  Timezone,
  TMDBDateString,
  TMDBObject,
  TrendingResult,
  TrendingTimeWindow,
  TVAppendToResponse,
  TVDetails,
  TVDetailsOptions,
  TVSeasonAppendToResponse,
  TVSeasonDetails,
  TVSeasonDetailsOptions,
  TVSearchOptions,
  TVSearchResult,
  TVSummary,
  Video,
  VideosResponse,
} from './types'
